IF (NOT EXISTS (SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'Cloudinary_DamSettings')
)
BEGIN
	CREATE TABLE [dbo].[Cloudinary_DamSettings](
		[SettingsID] INT NOT NULL IDENTITY(1,1),
		[SettingsGUID] [UNIQUEIDENTIFIER] NOT NULL,
		[WebsiteChannelID] INT NOT NULL,
		[CloudName] NVARCHAR(1024) NOT NULL,
		[ApiKey] NVARCHAR(1024) NOT NULL,
		[ApiSecret] NVARCHAR(1024) NOT NULL,
		[UseSaml] BIT NOT NULL CONSTRAINT DF__UseSaml DEFAULT(0),
		[UseIframeSupportForSaml] BIT NOT NULL CONSTRAINT DF__UseIframeSupportForSaml DEFAULT(0),
		[DefaultTransformations] NVARCHAR(MAX) NULL,
	CONSTRAINT [UQ__Cloudinary_DamSettings] UNIQUE ([WebsiteChannelID]),
	CONSTRAINT [PK__Cloudinary_DamSettings] PRIMARY KEY CLUSTERED
	(
		[SettingsID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END